baseURL = "https://ltns.nl"
locale = "en"
title = "Sten Lootens"
theme = ["PaperMod"]
enableRobotsTXT = true

[params]
mainSections = []
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[[params.socialIcons]]
name = "email"
url = "mailto:sten@ltns.nl"

[[params.socialIcons]]
name = "github"
url = "https://github.com/SteloNLD"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/stenlootens/"

[[menus.main]]
name = "Notes"
url = "/notes"
weight = 10

[[menus.main]]
name = "References"
url = "/references"
weight = 20

[[menus.main]]
name = "Now"
url = "/now"
weight = 30

[[menus.main]]
name = "About"
url = "/about"
weight = 40

[markup]
  [markup.highlight]
    style = "github"
